@rootAPI = http://localhost:8188/event-ticketing/api/v1



GET {{rootAPI}}/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQ2NjQ4MjIsImV4cCI6MTczNDY2NTcyMn0.7xsvp_Y31t1zgtDmVhe0RFWLhN0kGGBB0upUcI9tUz8
