@rootAPI = http://localhost:8188/event-ticketing/api/v1

##POST
POST {{rootAPI}}/user/register
Content-Type: application/json

{
    "name":"Srijan Dahal",
    "email":"a@1a.com",
    "password":"kathmandu",
    "type":"admin",
    "address":"Burwood"
}

